### ISSUE TITLE
Windows 7 Python 3.6

### ISSUE THREAD

**Issue by pedrodj** [DarkSpiritz/DarkSpiritz#12]
Hi DarkSpiritz

installed all dependencies, run ./start.py, created an username but

**

      [19:52] Connected to a network.
      [19:52] Local IP Address: 192.168.1.8
Traceback (most recent call last):
  File "start.py", line 75, in <module>
    welcome.welcome()
  File "C:\Python\DarkSpiritz\core\welcome.py", line 69, in welcome
    print(welcometext)
  File "C:\Python36\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 8-14: character maps to <undefined>

Any help?

**Comment by M4cs** [comment]
Added a line to encode in UTF-8. It should fix the problem. #

**Comment by M4cs** [comment]
Try repulling. If issue isnt fixed make a new issue.
